name: appcenter_release_manager
description: Download appcenter updates straight from your iOS or Android app.
homepage: https://github.com/vanlooverenkoen/flutter_appcenter_release_manager
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.vanlooverenkoen.appcenter_release_manager
        pluginClass: AppcenterReleaseManagerPlugin
      ios:
        pluginClass: AppcenterReleaseManagerPlugin
