name: appcenter_release_manager
description: Download appcenter updates straight from your iOS or Android app.
homepage: https://github.com/vanlooverenkoen/flutter_appcenter_release_manager
version: 3.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.1.12
  universal_io: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.vanlooverenkoen.appcenter_release_manager
        pluginClass: AppcenterReleaseManagerPlugin
      ios:
        pluginClass: AppcenterReleaseManagerPlugin
