name: appcenter_release_manager
description: Download appcenter updates straight from your iOS or Android app.
homepage: https://github.com/vanlooverenkoen/flutter_appcenter_release_manager
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.vanlooverenkoen.appcenter_release_manager
        pluginClass: AppcenterReleaseManagerPlugin
      ios:
        pluginClass: AppcenterReleaseManagerPlugin
