name: appcenter_release_manager
description: Download appcenter updates straight from your iOS or Android app.
homepage: https://github.com/impaktfull/flutter_appcenter_release_manager
version: 4.0.1
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  url_launcher: ^6.2.4
  universal_io: ^2.2.2
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.impaktfull.appcenter_release_manager
        pluginClass: AppcenterReleaseManagerPlugin
      ios:
        pluginClass: AppcenterReleaseManagerPlugin
