name: Sanity

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2.8.0
      with:
        channel: 'stable'
    - run: flutter packages get
    - run: dart run ./tool/check_for_credentials.dart

