name: Flutter Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2.8.0
      with:
        channel: 'stable'
    - run: flutter packages get
    - run: dart run ./tool/coverage/test_coverage_helper.dart
    - run: flutter test --coverage
    - run: dart run ./tool/coverage/filter_test_coverage.dart
    - run: dart run ./tool/coverage/test_check_coverage.dart
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
