name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Flutter action
      - uses: subosito/flutter-action@v2.8.0
      - name: Install dependencies
        run: flutter packages get
      - name: Analyze
        run: flutter analyze
